services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1ntegris  # Remplace par un mot de passe fort
      MYSQL_DATABASE: cloud_servicesdb        # Aligne avec settings.py
      MYSQL_USER: integris                    # Aligne avec settings.py
      MYSQL_PASSWORD: 1ntegris                # Aligne avec settings.py
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"         # phpMyAdmin dispo sur localhost:8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1ntegris
    depends_on:
      - db

  backend:
    build: ./backend
    
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=cloud_servicesdb              # Aligne avec settings.py
      - DB_USER=integris                     # Aligne avec settings.py
      - DB_PASSWORD=1ntegris                 # Aligne avec settings.py
      - DB_PORT=3306

  frontend:
    build: ./frontend/react-cloud
    depends_on:
      - backend

  web:
    image: php:8.1-apache
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - /home/ftpuser/build:/var/www/html
      - ./frontend/react-cloud/build:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - frontend
      - backend
    links:
      - backend:backend
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      /bin/sh -c "a2enmod proxy &&
                a2enmod proxy_http &&
                chown -R www-data:www-data /var/www/html &&
                exec apache2-foreground"

volumes:
  db_data: