# Generated by Django 5.1.6 on 2025-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('STORAGE', 'Storage'), ('NETWORK', 'Network'), ('SECURITY', 'Security'), ('AI', 'AI/ML'), ('ANALYTICS', 'Analytics'), ('DEVOPS', 'DevOps'), ('DATABASE', 'Database'), ('COMPUTE', 'Compute'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
